### ISSUE TITLE
Which branch or commit of DRAMSim is used for performance estimation of kmh?

### ISSUE THREAD

**Issue by shinezyy** [OpenXiangShan/XiangShan-doc#117]
Are you using cosim-kmh ([fca1245](https://github.com/OpenXiangShan/DRAMsim3/commit/fca1245acfff01a4f18830cd15675e904564aa2a)) for performance test?

@Maxpicca-Li

**Comment by Maxpicca-Li** [comment]
> Are you using cosim-kmh ([fca1245](https://github.com/OpenXiangShan/DRAMsim3/commit/fca1245acfff01a4f18830cd15675e904564aa2a)) for performance test?
> 
> @Maxpicca-Li

Yes (Sorry, because I didn't pay attention to this repository, I didn't reply in time)
