### ISSUE TITLE
crng init失败

### ISSUE THREAD

**Issue by hongwuya** [OpenXiangShan/XiangShan-doc#134]
现象：linux kernel日志中未打印 random: crng init done
我认为是crng未初始化成功，导致后续调用getrandom时陷入死循环。
请问要做哪些修改？
riscv-linux版本：https://github.com/OpenXiangShan/riscv-linux nanshan分支
risck-pk版本:https://github.com/OpenXiangShan/riscv-pk noop分支
riscv-rootfs版本:https://github.com/OpenXiangShan/riscv-rootfs master 分支
问题用例:spec2017 521wrf用例

**Comment by eastonman** [comment]
如果您是在香山RTL上运行，请到 [OpenXiangShan/XiangShan](https://github.com/OpenXiangShan/XiangShan) 提 issue，并按照issue 模板提供详细的信息。如果是在 NEMU 等其他东西上运行，请到对应的仓库提 issue。
