### ISSUE TITLE
spec2017 521用例陷入死循环无法终止

### ISSUE THREAD

**Issue by hongwuya** [OpenXiangShan/XiangShan-doc#137]
问题描述：我使用nemu 跑spec2017 521用例的workload，执行profiling的过程中，发现程序一直陷入死循环，无法终止。
workload的生成过程参考的XiangShan 官方文档，bbl+linux+application
riscv-linux：https://github.com/OpenXiangShan/riscv-linux nanshan分支
risck-pk版本:https://github.com/OpenXiangShan/riscv-pk noop分支
riscv-rootfs版本:https://github.com/OpenXiangShan/riscv-rootfs master 分支
根据我的初步排查，由于linux kernel 启动过程中crng未初始化成功，导致程序在getrandom函数中无法跳出，请问如何配置能使得crng正确初始化？
生成的profiling log见附件521_err.txt
[521_err.txt](https://github.com/user-attachments/files/17566990/521_err.txt)

**Comment by xyyy1420** [comment]
https://github.com/OpenXiangShan/CPU2017LiteWrapper/issues/1 已经在这里解决
