### ISSUE TITLE
编译香山工具链时编译后工具套件不完整

### ISSUE THREAD

**Issue by cuipingzhang** [OpenXiangShan/XiangShan-doc#14]
按照文档要求替换了riscv-gcc和riscv-binutils到指定分支，编译后工具套件找那个缺少gcc   g++  等工具，但是又 ar  as ld等，log如下，粘了一部分，因为这一部分就在check的时候就指出不生成gcc  g++等，在这之前还报错了缺少isl，不知是否和这个有关
rm -rf stamps/build-binutils-linux build-binutils-linux
rm -rf stamps/build-gdb-linux build-gdb-linux
mkdir build-binutils-linux
mkdir build-gdb-linux
cd build-binutils-linux && CC_FOR_TARGET=riscv64-unknown-linux-gnu-gcc /home/zcc/toolchain/riscv-gnu-toolchain/build/../riscv-binutils/configure \
	--target=riscv64-unknown-linux-gnu \
	 \
	--prefix=/home/zcc/toolchain/riscv \
	--with-sysroot=/home/zcc/toolchain/riscv/sysroot \
	--disable-multilib \
	 \
	--disable-werror \
	--disable-nls \
	--with-expat=yes  \
	--disable-gdb \
	--disable-sim \
	--disable-libdecnumber \
	--disable-readline
cd build-gdb-linux && CC_FOR_TARGET=riscv64-unknown-linux-gnu-gcc /home/zcc/toolchain/riscv-gnu-toolchain/build/../riscv-gdb/configure \
	--target=riscv64-unknown-linux-gnu \
	 \
	--prefix=/home/zcc/toolchain/riscv \
	--with-sysroot=/home/zcc/toolchain/riscv/sysroot \
	--disable-multilib \
	 \
	--disable-werror \
	--disable-nls \
	--with-expat=yes  \
	--enable-gdb \
	--disable-gas \
	--disable-binutils \
	--disable-ld \
	--disable-gold \
	--disable-gprof
checking build system type... checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... riscv64-unknown-linux-gnu
riscv64-unknown-linux-gnu
checking for a BSD-compatible install... checking for a BSD-compatible install... /usr/bin/install -c
checking whether ln works... /usr/bin/install -c
checking whether ln works... yes
checking whether ln -s works... yes
checking for a sed that does not truncate output... yes
checking whether ln -s works... yes
checking for a sed that does not truncate output... /usr/bin/sed
checking for gawk... /usr/bin/gawk
/usr/bin/sed
checking for gawk... /usr/bin/gawk
configure: WARNING: neither ld nor gold are enabled
checking for gdbserver support... no
checking for gdbserver support... checking for gcc... gcc
no
checking for gcc... gcc
checking whether the C compiler works... checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 

checking whether we are cross compiling... checking whether we are cross compiling... no
no
checking for suffix of object files... checking for suffix of object files... o
checking whether we are using the GNU C compiler... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... yes
checking for gcc option to accept ISO C89... none needed
checking for g++... g++
none needed
checking for g++... g++
checking whether we are using the GNU C++ compiler... checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking whether g++ accepts -g... yes
yes
checking whether g++ accepts -static-libstdc++ -static-libgcc... checking whether g++ accepts -static-libstdc++ -static-libgcc... yes
checking for gnatbind... yes
no
checking for gnatmake... no
checking whether compiler driver understands Ada... checking for gnatbind... no
checking for gnatmake... no
checking whether compiler driver understands Ada... no
checking how to compare bootstrapped objects... no
checking how to compare bootstrapped objects... cmp --ignore-initial=16 $$f1 $$f2
checking for objdir... cmp --ignore-initial=16 $$f1 $$f2
checking for objdir... .libs
.libs
checking for isl 0.15 or later... checking for isl 0.15 or later... no
required isl version is 0.15 or later
no
required isl version is 0.15 or later
*** This configuration is not supported in the following subdirectories:
     gdbserver binutils gas gprof
    (Any other directories should still work fine.)
*** This configuration is not supported in the following subdirectories:
     gdbserver readline libdecnumber sim gdb
    (Any other directories should still work fine.)
checking for default BUILD_CONFIG... 
checking for --enable-vtable-verify... no
checking for default BUILD_CONFIG... 
checking for --enable-vtable-verify... no
checking for bison... bison -y
checking for bison... bison
checking for gm4... no
checking for gnum4... no
checking for m4... m4
checking for flex... flex
checking for flex... flex
checking for makeinfo... makeinfo
checking for bison... bison -y
checking for bison... bison
checking for gm4... no
checking for gnum4... no
checking for m4... m4
checking for flex... flex
checking for flex... flex
checking for makeinfo... makeinfo
checking for expect... checking for expect... no
no
checking for runtest... checking for runtest... no
no
checking for ar... checking for ar... ar
ar
checking for as... checking for as... as
as
checking for dlltool... checking for dlltool... no
no
checking for ld... checking for ld... ld
ld
checking for lipo... checking for lipo... no
no
checking for nm... nm
checking for ranlib... checking for nm... ranlib
nm
checking for strip... checking for ranlib... strip
ranlib
checking for windres... checking for strip... no
strip
checking for windmc... checking for windres... no
no
checking for objcopy... checking for windmc... objcopy
no
checking for objdump... checking for objcopy... objcopy
objdump
checking for objdump... checking for readelf... objdump
readelf
checking for readelf... checking for cc... (cached) riscv64-unknown-linux-gnu-gcc
checking for gcc... (cached) readelf
riscv64-unknown-linux-gnu-gcc
checking for cc... (cached) riscv64-unknown-linux-gnu-gcc
checking for gcc... (cached) riscv64-unknown-linux-gnu-gcc
checking for riscv64-unknown-linux-gnu-c++... no
checking for riscv64-unknown-linux-gnu-g++... checking for riscv64-unknown-linux-gnu-c++... no
checking for riscv64-unknown-linux-gnu-cxx... no
checking for riscv64-unknown-linux-gnu-g++... no
no
checking for riscv64-unknown-linux-gnu-gxx... checking for riscv64-unknown-linux-gnu-cxx... no
no
checking for riscv64-unknown-linux-gnu-gxx... no
checking for riscv64-unknown-linux-gnu-gcc... checking for riscv64-unknown-linux-gnu-gcc... no
no
checking for riscv64-unknown-linux-gnu-gfortran... checking for riscv64-unknown-linux-gnu-gfortran... no
no
checking for riscv64-unknown-linux-gnu-gccgo... checking for riscv64-unknown-linux-gnu-gccgo... no
no
checking for riscv64-unknown-linux-gnu-ar... riscv64-unknown-linux-gnu-ar
checking for riscv64-unknown-linux-gnu-as... riscv64-unknown-linux-gnu-as
checking for riscv64-unknown-linux-gnu-ar... riscv64-unknown-linux-gnu-ar
checking for riscv64-unknown-linux-gnu-dlltool... checking for riscv64-unknown-linux-gnu-as... no
riscv64-unknown-linux-gnu-as
checking for riscv64-unknown-linux-gnu-ld... riscv64-unknown-linux-gnu-ld
checking for riscv64-unknown-linux-gnu-dlltool... no
checking for riscv64-unknown-linux-gnu-lipo... no
checking for riscv64-unknown-linux-gnu-ld... riscv64-unknown-linux-gnu-ld
checking for riscv64-unknown-linux-gnu-lipo... checking for riscv64-unknown-linux-gnu-nm... no
riscv64-unknown-linux-gnu-nm
checking for riscv64-unknown-linux-gnu-nm... checking for riscv64-unknown-linux-gnu-objcopy... riscv64-unknown-linux-gnu-objcopy
riscv64-unknown-linux-gnu-nm
checking for riscv64-unknown-linux-gnu-objdump... riscv64-unknown-linux-gnu-objdump
checking for riscv64-unknown-linux-gnu-ranlib... riscv64-unknown-linux-gnu-ranlib
checking for riscv64-unknown-linux-gnu-objcopy... checking for riscv64-unknown-linux-gnu-readelf... riscv64-unknown-linux-gnu-readelf
riscv64-unknown-linux-gnu-objcopy
checking for riscv64-unknown-linux-gnu-strip... riscv64-unknown-linux-gnu-strip
checking for riscv64-unknown-linux-gnu-objdump... riscv64-unknown-linux-gnu-objdump
checking for riscv64-unknown-linux-gnu-windres... no
checking for riscv64-unknown-linux-gnu-ranlib... riscv64-unknown-linux-gnu-ranlib
checking for riscv64-unknown-linux-gnu-windmc... no
checking where to find the target ar... checking for riscv64-unknown-linux-gnu-readelf... just compiled
checking where to find the target as... riscv64-unknown-linux-gnu-readelf
just compiled
checking where to find the target cc... checking for riscv64-unknown-linux-gnu-strip... riscv64-unknown-linux-gnu-strip
pre-installed
checking where to find the target c++... checking for riscv64-unknown-linux-gnu-windres... no
checking for riscv64-unknown-linux-gnu-windmc... no
checking where to find the target ar... pre-installed
checking where to find the target c++ for libstdc++... pre-installed
checking where to find the target as... pre-installed
checking where to find the target dlltool... just compiled
checking where to find the target gcc... pre-installed
checking where to find the target cc... pre-installed
checking where to find the target gfortran... pre-installed
checking where to find the target c++... pre-installed
checking where to find the target gccgo... pre-installed
checking where to find the target c++ for libstdc++... pre-installed
checking where to find the target ld... just compiled
checking where to find the target lipo... pre-installed
checking where to find the target dlltool... pre-installed
checking where to find the target nm... just compiled
checking where to find the target objcopy... just compiled
checking where to find the target objdump... just compiled
checking where to find the target ranlib... just compiled
checking where to find the target readelf... just compiled
checking where to find the target strip... just compiled
checking where to find the target windres... just compiled
checking where to find the target windmc... just compiled
checking whether to enable maintainer-specific portions of Makefiles... no
pre-installed
checking where to find the target gcc... pre-installed
checking where to find the target gfortran... pre-installed
checking where to find the target gccgo... pre-installed
checking where to find the target ld... pre-installed
checking where to find the target lipo... pre-installed
checking where to find the target nm... pre-installed
checking where to find the target objcopy... pre-installed
checking where to find the target objdump... pre-installed
checking where to find the target ranlib... pre-installed

checking where to find the target readelf... pre-installed
checking where to find the target strip... pre-installed
checking where to find the target windres... pre-installed
checking where to find the target windmc... pre-installed
checking whether to enable maintainer-specific portions of Makefiles... no
configure: creating ./config.status
configure: creating ./config.status
config.status: creating Makefile
config.status: creating Makefile
make -C build-binutils-linux

**Comment by ljwljwljwljw** [comment]
由于您提供的信息有限，我们无法帮您定位问题。建议您清空浏览器缓存，重新加载[工具链文档](https://xiangshan-doc.readthedocs.io/zh_CN/latest/compiler/gnu_toolchain/)以确保您看的是最新的文档，按照文档进行操作后如果仍然存在问题，请以给出您运行编译命令的log以及错误log，方便我们定位。
