### ISSUE TITLE
checkpoint的生成

### ISSUE THREAD

**Issue by cuipingzhang** [OpenXiangShan/XiangShan-doc#16]
checkpoint的生成中，该“Checkpoint的生成.md文件”文档中采用riscv64-nemu-interpreter的--simpoint-profile来生成用于simpoint的BBV文件，
riscv64-nemu-interpreter workload.bin -D /home/user/spec_cpt -w workloadName -C run_spec -b --simpoint-profile --interval 100000000
1.该命令行中workload.bin是可执行文件吗，虽然后缀是bin，应该是类似elf的该执行文件吧
2.如果该可执行文件执行时需要后面跟输入参数，如一个文件，该怎么添加参数，如cpu2006中的某一个测试项，

这个bin文件使用OBJCOPY从可执行文件生成的吗

**Comment by shinezyy** [comment]
1. workload.bin is generated from objcopy. It is bare metal workload instead of elf.
2. We run SPEC after booting Linux. If your want to take checkpoints for SPECCPU, you should run Linux  and let Linux to start SPEC right after boot.

**Comment by cuipingzhang** [comment]
> 1. workload.bin is generated from objcopy. It is bare metal workload instead of elf.
> 2. We run SPEC after booting Linux. If your want to take checkpoints for SPECCPU, you should run Linux  and let Linux to start SPEC right after boot.

  我想用riscv64-nemu-interpreter的--simpoint-profile来生成cpu2006某个测试项的BBV，比如400.perlbench，基于linux编译完成后用objcopy生成了bin文件，但是该测试项执行时后面会跟参数，cpu2006的测试我采用的和你们一样的方法，单独编译执行，不是用runspec指令，那我生成perlbench.bin后怎么写这条生成BBV的指令，perlbench执行需要的参数怎么添加进去

**Comment by cuipingzhang** [comment]
> 1. workload.bin is generated from objcopy. It is bare metal workload instead of elf.
> 2. We run SPEC after booting Linux. If your want to take checkpoints for SPECCPU, you should run Linux  and let Linux to start SPEC right after boot.

针对第一条，确认一下，我的400.perlbench基于Linux生成的可执行文件，是可以用objcopy直接从该可执行文件转换来的吗

**Comment by cuipingzhang** [comment]
我又重新看了下文档，你这个workload.bin是基于裸机的，不是基于linux内核的是吗，可是cpu2006的测试不是基于linux运行的吗

**Comment by shinezyy** [comment]
Most SPEC benchmarks depend on *nix environment. Bare metal environment is not enough for them. So you have to run them in Linux.

**Comment by cuipingzhang** [comment]
> Most SPEC benchmarks depend on *nix environment. Bare metal environment is not enough for them. So you have to run them in Linux.

能针对我上面的两个问题具体回答吗

**Comment by shinezyy** [comment]
我就是在直接回答你啊。

跟你说了，裸机跑不起来perlbench，因为裸机没有运行时。

“perlbench执行需要的参数怎么添加进去？”
没有Linux、没有运行时，怎么传？

就算传进去了又怎么样？perlbench要用系统调用啊，你去给NEMU挨个实现系统调用？再虚拟一个文件系统？

**Comment by cuipingzhang** [comment]
那我这么问吧，可以用riscv64-nemu-interpreter生成cpu2006中400.perlbench的BBV文件吗

**Comment by shinezyy** [comment]
可以

**Comment by shinezyy** [comment]
Run Linux and let Linux to start perlbench right after boot.

**Comment by cuipingzhang** [comment]
那这个400.perlbench的workload.bin是怎么生成的

**Comment by shinezyy** [comment]
这个400.perlbench的workload.bin是bbl + linux + perlbench

需要你自己去构建

https://github.com/OpenXiangShan/XiangShan-doc/blob/main/tutorial/others/Linux%20Kernel%20%E7%9A%84%E6%9E%84%E5%BB%BA.md

**Comment by cuipingzhang** [comment]
1.文档中有这样一句话“workload （非 可执行文件格式，需使用 objcopy 命令进行处理）”
这个riscv64-nemu-interpreterc后面跟的workload.bin  其实并不是简单的用objcopy从可执行文件（在Linux系统上编译好的400.perlbench的可执行文件）转换来的是吗
2.riscv64-nemu-interpreter workload.bin -D /home/user/spec_cpt -w workloadName -C run_spec -b --simpoint-profile --interval 100000000
执行这条指令需要做什么准备，我编译好了NEMU生成了risczv64-nemu-interpreter可执行文件，然后再生成一个workload.bin不就可以了吗，我看文档里也没有别的需求了啊

**Comment by cuipingzhang** [comment]
> 这个400.perlbench的workload.bin是bbl + linux + perlbench
> 
> 需要你自己去构建
> 
> https://github.com/OpenXiangShan/XiangShan-doc/blob/main/tutorial/others/Linux%20Kernel%20%E7%9A%84%E6%9E%84%E5%BB%BA.md

这个workload.bin  我每测一个测试项都要重新生成一次，但里面除了具体的测试项还包含bbl+linux  也就是说每生成一个测试项的BBV，执行一次riscv64-nemu-interpreter workload.bin，每次的执行中bbl+linux都跟着跑了一遍?

**Comment by cuipingzhang** [comment]
> 这个400.perlbench的workload.bin是bbl + linux + perlbench
> 
> 需要你自己去构建
> 
> https://github.com/OpenXiangShan/XiangShan-doc/blob/main/tutorial/others/Linux%20Kernel%20%E7%9A%84%E6%9E%84%E5%BB%BA.md

连接中文档介绍的bbl.bin和Checkpoint的生成.md文档中“workload （非 可执行文件格式，需使用 objcopy 命令进行处理）”的workload是一个东西吗
看链接文档bbl.bin应该包括bbl + linux + perlbench，用objcopy生成的workload是什么，再哪用

**Comment by BigWhiteDog** [comment]
> > 这个400.perlbench的workload.bin是bbl + linux + perlbench
> > 需要你自己去构建
> > https://github.com/OpenXiangShan/XiangShan-doc/blob/main/tutorial/others/Linux%20Kernel%20%E7%9A%84%E6%9E%84%E5%BB%BA.md
> 
> 连接中文档介绍的bbl.bin和Checkpoint的生成.md文档中“workload （非 可执行文件格式，需使用 objcopy 命令进行处理）”的workload是一个东西吗 看链接文档bbl.bin应该包括bbl + linux + perlbench，用objcopy生成的workload是什么，再哪用

NEMU称呼的workload为全系统的内存镜像，需要自己用objcopy制作成binary以便加载入内存中等待启动
测试某个程序如perlbench时称呼其为运行在linux上的某个workload，是ELF文件

**Comment by cuipingzhang** [comment]
2. 在此基础上，介绍如何在 Linux 下跑 BusyBox 以及一些简单的应用程序
重新配置 Linux Kernel
到 riscv-linux 目录
使用 fpga_defconfig 配置，命令为 make ARCH=riscv CROSS_COMPILE=riscv64-linux-gnu- defconfig fpga_defconfig
根据自己的需求酌情通过 menuconfig 做修改，命令为 make ARCH=riscv CROSS_COMPILE=riscv64-linux-gnu- menuconfig，其中一个较为必要的修改是将 initramfs 的 source 从 ${RISCV_ROOTFS_HOME}/rootfsimg/initramfs.txt 改为 ${RISCV_ROOTFS_HOME}/rootfsimg/initramfs-autorun.txt
酌情修改 rootfs
到 riscv-rootfs 目录下的 rootfsimg 目录
酌情修改 initramfs-autorun.txt 和 inittab 中的内容，以在 Linux 启动过后跑你所想要的程序（默认情况下是 stream 和 redis）
重新配置 BBL
到 riscv-pk 目录
make clean 后运行 make -j 生成 bbl.bin，让香山或者 NEMU 跑它

最后的这个bbl.bin就是riscv64-nemu-interpreter workload.bin -D /home/user/spec_cpt -w workloadName -C run_spec -b --simpoint-profile --interval 100000000这条指令里的workload.bin吧，也就是说我得把自己想测的cpu2006  copy到riscv-tootfs
的app下，还得修改 initramfs-autorun.txt 和 inittab 中的内容，使linux启动后跑CPU2006？

**Comment by cuipingzhang** [comment]
![image](https://user-images.githubusercontent.com/51359944/165697067-044d3fee-e930-4364-9763-d4a808e89c07.png)

![image](https://user-images.githubusercontent.com/51359944/165697174-8a290733-0466-4d54-8195-17dc5e4be2ae.png)
1. 确认一下，上图的bbl.bin就是下图中的workload.bin吧
2. 
![image](https://user-images.githubusercontent.com/51359944/165697468-db6a2dc0-51c7-4db4-b0be-6dbb88e8ac07.png)
这条指令我还用执行吗  ，只是想在NEMU上生成BBV文件。
3.修改rootfs，我是不是得把自己想测试的CPU2006  copy到riscv-rootfs/apps目录下，然后还得修改 initramfs-autorun.txt 和 inittab 中的内容，使linux再NEMU上启动后跑cpu2006

**Comment by BigWhiteDog** [comment]
1. 是的
2.&3 linux内核可以按你自己的需要选择config，我们也只是提供了一个config，请理解initramfs的意义；按流程来讲差不多是这样的

**Comment by cuipingzhang** [comment]
emu_defconfig   menuconfig  fpga_defconfig这三个config分别是配置什么的

**Comment by BigWhiteDog** [comment]
> emu_defconfig menuconfig fpga_defconfig这三个config分别是配置什么的

这三个其中有一个不是config，这是编译linux的基本知识，请自行了解

**Comment by cuipingzhang** [comment]
![image](https://user-images.githubusercontent.com/51359944/165871675-abfba431-f257-44f2-87e4-b643ca2c567a.png)

前两个有什么区别吗，还是就是一个工具链，只不过前缀不同

**Comment by cuipingzhang** [comment]
![image](https://user-images.githubusercontent.com/51359944/165876482-35fdb9b4-fdb7-471b-a600-35cc7a03b149.png)
NOOP_HOME是哪个

**Comment by cuipingzhang** [comment]
![image](https://user-images.githubusercontent.com/51359944/165876568-01eef636-d6da-47a0-b42e-3adfd3f13de6.png)
这步怎么操作，修改哪个文件

**Comment by BigWhiteDog** [comment]
> ![image](https://user-images.githubusercontent.com/51359944/165871675-abfba431-f257-44f2-87e4-b643ca2c567a.png)
> 
> 前两个有什么区别吗，还是就是一个工具链，只不过前缀不同

是不同的工具链，请参考https://xiangshan-doc.readthedocs.io/zh_CN/latest/compiler/gnu_toolchain/

另外，请到XiangShan主repo下进行提问，请勿在doc中提问技术问题

**Comment by cuipingzhang** [comment]
> 个有什么区别吗，还是就是一个工具链，只不
该问题中我问的时前两个riscv64-linux-gnu-，riscv64-unknown-linux-gnu-，你给的链接是后两个。
另：这些问题都是文档看的，都是针对文档的介绍提的问题。

**Comment by cuipingzhang** [comment]
> > ![image](https://user-images.githubusercontent.com/51359944/165871675-abfba431-f257-44f2-87e4-b643ca2c567a.png)
> > 前两个有什么区别吗，还是就是一个工具链，只不过前缀不同
> 
> 是不同的工具链，请参考https://xiangshan-doc.readthedocs.io/zh_CN/latest/compiler/gnu_toolchain/
> 
> 另外，请到XiangShan主repo下进行提问，请勿在doc中提问技术问题

该问题中我问的时前两个riscv64-linux-gnu-，riscv64-unknown-linux-gnu-，你给的链接是后两个。
另：这些问题都是文档看的，都是针对文档的介绍提的问题。

**Comment by shinezyy** [comment]
你问的一些问题不是香山specific的问题，而是通用问题。这些问题你应该自己去搜索，网上有现成答案，我们没有义务给这些通用问题做QA。

例如，这个问题：
> 软链接到noop.dtsi
> 这步怎么操作，修改哪个文件

再例如
> riscv64-linux-gnu-，riscv64-unknown-linux-gnu- 有什么区别

**Comment by shinezyy** [comment]
针对后一个问题，根据我搜索的结果，unknown-linux-gnu和linux-gnu应该没有什么区别：https://unix.stackexchange.com/questions/206410/why-gcc-show-unknown-in-target-x86-64-unknown-linux-gnu-in-arch-linux

这个答案也说明，这个问题不是xiangshan specific的，甚至不是RISC-V specific的，并且是在互联网上存在现成答案的。

**Comment by BigWhiteDog** [comment]
> 

原因是其中的

> > > ![image](https://user-images.githubusercontent.com/51359944/165871675-abfba431-f257-44f2-87e4-b643ca2c567a.png)
> > > 前两个有什么区别吗，还是就是一个工具链，只不过前缀不同
> > 
> > 
> > 是不同的工具链，请参考https://xiangshan-doc.readthedocs.io/zh_CN/latest/compiler/gnu_toolchain/
> > 另外，请到XiangShan主repo下进行提问，请勿在doc中提问技术问题
> 
> 该问题中我问的时前两个riscv64-linux-gnu-，riscv64-unknown-linux-gnu-，你给的链接是后两个。 另：这些问题都是文档看的，都是针对文档的介绍提的问题。

这里指定成两个工具链的原因是，香山相关仓库以及应用中有些编译指定了riscv64-linux-gnu-工具链，另一些指定了riscv64-unknown-linux-gnu-，因此在这里说明了两个工具链以方便一键编译各个应用，实际上你软链接他们两个为同一个工具链也没有问题。
另：若使用Ubuntu类发行版，可以apt快速安装riscv64-linux-gnu-工具链

**Comment by sashimi-yzh** [comment]
社区应该是用来反馈那些真实存在的问题, 你这个问题纯粹是你自己不想动手, 所以找社区开发者来问: 你完全可以自己试着跑, 跑出错误之后尝试自己解决, 实在解决不了才带着错误来提问. 你说"问一下比较好", 也只是说明你不想花时间去自己解决这个问题.

另外, 不要把开源社区当做你学习的课堂, 社区开发者不是你的老师, 你的某些提问不仅不能给社区带来价值, 而且你也并没有为这些提问向社区开发者支付任何报酬, 大家没有义务教你学习. 基础不牢固, 就先自己补好功课再进社区.
