### ISSUE TITLE
香山性能瓶颈分析PPT参考文献

### ISSUE THREAD

**Issue by zhaohaosen-cpu** [OpenXiangShan/XiangShan-doc#33]
没有找到第三页的IBM性能建模的参考文献，能否说明一下论文的名称呢，感谢！

**Comment by Gao-Zeyu** [comment]
1. P. Bose, T. M. Conte and T. M. Austin, “Challenges in processor modeling and validation,” IEEE Micro, vol. 19, no. 3, pp. 9-13, May/June 1999. 
2. Ailamaki A, DeWitt D J, Hill M D, et al., 1999. DBMSs on a modern processor: Where does time go?[C]//VLDB’99, Proceedings of 25th International Conference on Very Large Data Bases, September 7-10, 1999, Edinburgh, Scotland, UK: CONF: 266-277.
3. Eyerman S, Eeckhout L, Karkhanis T, et al., 2006. A performance counter architecture for computing accurate CPI components[J]. ACM SIGPLAN Notices, 41(11): 175-184.
