### ISSUE TITLE
对于 Cache别名问题 章节表述的一些疑问

### ISSUE THREAD

**Issue by LingZichao** [OpenXiangShan/XiangShan-doc#40]
https://github.com/OpenXiangShan/XiangShan-doc/blob/ae27c4c9081f95074d40a0fc9b6b06adc4687df6/docs/huancun/cache_alias.md?plain=1#L3

对Cache别名问题的定义中，认为两个`同一物理页在Cache中缓存了两份`造成了一些一致性错误。
结合图片来看，我认为这部分应该是同一物理页的`物理块`在Cache中缓存了两份。
定义这部分表述应该做一些修改，不知道是不是我哪里理解有错？

**Comment by wakafa1** [comment]
您说得更准确，确实应当表述为“归属于同一物理页的物理块在Cache中缓存了两份”，非常感谢勘误！
我们后续将提交 patch 更新。
