### ISSUE TITLE
2023 年的RISC-V峰会都结束了，资料可以更新到 2023 啦

### ISSUE THREAD

**Issue by anzipomelo** [OpenXiangShan/XiangShan-doc#62]

**Comment by poemonsense** [comment]
2023年峰会的ppt已经上传：https://github.com/OpenXiangShan/XiangShan-doc/tree/main/slides

也可以关注https://xiangshan-doc.readthedocs.io/zh-cn/latest/tutorials/talks/，包含所有以往的公开报告列表

**Comment by poemonsense** [comment]
微结构的文档目前都是南湖架构的，昆明湖架构的会在之后更新
