### ISSUE TITLE
NEMU 跑 Debian 出现错误

### ISSUE THREAD

**Issue by erdevonmatteo11** [OpenXiangShan/XiangShan-doc#8]
附件是 NEMU 的打印信息

[20220308_nemu_debian.log](https://github.com/OpenXiangShan/XiangShan-doc/files/8210851/20220308_nemu_debian.log)

**Comment by wakafa1** [comment]
根据您的 Log，我初步判断是 dts 的问题，请修改 bootargs = "root=/dev/mmcblk0**p1** rootfstype=ext4 ro rootwait earlycon";（需要指定 p1 分区）
请参考 https://github.com/OpenXiangShan/NEMU/tree/master/resource/sdcard

**Comment by erdevonmatteo11** [comment]
> 

请问是修改哪一个 dts ？我在您给的参考教程里看不到 dts 文件的路径。

**Comment by wakafa1** [comment]
riscv-pk/dts/noop.dts

**Comment by erdevonmatteo11** [comment]
> 
根据您的建议，我做了修改，似乎旧问题已解决；目前遇到了新的问题

[20220309_1.log](https://github.com/OpenXiangShan/XiangShan-doc/files/8211760/20220309_1.log)

**Comment by wakafa1** [comment]
该问题我无法复现，请检查 riscv-linux、riscv-pk 和 NEMU 是否为最新版本

**Comment by erdevonmatteo11** [comment]
>

经查，我去掉了对 mmc reg 地址的修改（保持原状，不改成 0xa3000000），重新编译 riscv-pk，然后 NEMU 成功运行了 Debian。
目前我发现了新的错误，似乎与 swap 分区有关。

[20220309_2.log](https://github.com/OpenXiangShan/XiangShan-doc/files/8213031/20220309_2.log)

**Comment by erdevonmatteo11** [comment]
> 

当 NEMU / Verilator 运行 Debian 时，如何合理地退出虚拟机环境，而不是用 ctrl+c 的方式？

**Comment by wakafa1** [comment]
用 Ctrl-C 就可以了，在 Verilator 仿真的时候我们会捕捉这个信号然后做收尾工作
