### ISSUE TITLE
riscv-pk打包bbl后启动时所有动态链接库均无法找到

### ISSUE THREAD

**Issue by YudeFang** [OpenXiangShan/XiangShan-doc#83]
![image](https://github.com/OpenXiangShan/XiangShan-doc/assets/49511258/1f25d973-8109-46d3-87a6-e8cce0e38f0a)
如图，nemu的log显示即使before_workload也无法进行任何动态链接，busybox我使用静态链接后可以正常工作了。请问这种情况该怎么解决，全改静态链接么

**Comment by xyyy1420** [comment]
[before_workload](https://github.com/OpenXiangShan/riscv-rootfs/blob/checkpoint/apps/before_workload/before_workload.c)完全没有任何依赖，更不用说libc了

**Comment by YudeFang** [comment]
可以提供下稳定的gcc版本么，我目前注释掉了所有spec有关的东西只跑beforeworkload和trap指定依然会报动态链接错误，我怀疑可能是gcc版本问题。

**Comment by xyyy1420** [comment]
[riscv-gnu-toolchains](https://github.com/riscv-collab/riscv-gnu-toolchain) 
- 另外，如果是香山维护的工具/文档等有问题，比如`NEMU`本身的问题，可以直接在对应的仓库提 issue
-  如果是 `linux kernel`或`busybox` 等不是香山维护的东西有问题，请去对应的仓库/mail list 提问题，这些问题如果提到香山的仓库中，将可能不会有任何回复

**Comment by YudeFang** [comment]
我在执行指令的脚本里尝试了执行ls /lib 我发现所有的动态链接库都有 但他不知道为啥就是找不到，请问是需要添加LD_LIBRARY_PATH么 如果要添加要修改哪个文件呢
![image](https://github.com/OpenXiangShan/XiangShan-doc/assets/49511258/ea1b274b-505d-4dd1-b7a1-6dd58cf73d71)

**Comment by shinezyy** [comment]
> 我在执行指令的脚本里尝试了执行ls /lib 我发现所有的动态链接库都有 但他不知道为啥就是找不到，请问是需要添加LD_LIBRARY_PATH么 如果要添加要修改哪个文件呢 ![image](https://private-user-images.githubusercontent.com/49511258/310355643-ea1b274b-505d-4dd1-b7a1-6dd58cf73d71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MzAwMTQsIm5iZiI6MTcwOTcyOTcxNCwicGF0aCI6Ii80OTUxMTI1OC8zMTAzNTU2NDMtZWExYjI3NGItNTA1ZC00ZGQxLWI3YTEtNmRkNThjZjczZDcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDEyNTUxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0MGZmYjRiMjgwMTZjY2M0ZTQ2YTMxNWJkYzRlMGM4MjQwZmRhNzFlNWZhYjMyZjZiM2RlOWUwMDM1YjRmNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.okgmTESmM5LdlmzID-34swfR1nxRSmKvS0gzuMIjg6U)

我们建议尝试用NEMU运行ready-to-run里面的linux.bin看能否运行。

其实Linux启动配置不属於香山这个组织应该回答的范围。虽然我们一般会尽力回答，但是你遇到的问题我们确实没遇到过，通过网络上提供的信息，我们暂时也没有什么线索。

你遇到的这个问题也让我们意识到我们现有方式的不足：
- 文档散乱
- 即使用户99% follow了散乱的文档，但是仍然可能因为本地其它环境导致workload生成出错。我们会在不远的未来尝试解决这个问题，比如提供docker或者虚拟机镜像。

1.

**Comment by YudeFang** [comment]
我解决了上面那个问题，通过往run.sh里面添加了这行命令
![image](https://github.com/OpenXiangShan/XiangShan-doc/assets/49511258/04c0addd-e7bb-467b-8bef-656631c6c4cf)
但是遇到了一个新的问题是spec中的程序又无法找到了
报错信息如下

===== Start running SPEC2006 =====

======== BEGIN mcf ========

[1;32mld-linux-riscv64-lp64d.so.1[m  [1;32mlibm.so.6[m

[1;32mlibc.so.6[m                    [1;32mlibpthread.so.0[m

[1;32mlibdl.so.2[m                   [1;32mlibresolv.so.2[m

+ md5sum /spec/astar_base

764318717d9e7f0f657133f6faf58247  /spec/astar_base

+ date -R

Thu, 01 Jan 1970 00:00:19 +0000

+ cd /spec_common

+ ./before_workload

+ cd ../spec

+ pwd

/spec

+ ls -al

total 4164

drwxr-xr-x    2 0        0                0 Mar  7  2024 [1;34m.[m

drwxr-xr-x   16 0        0                0 Jan  1 00:00 [1;34m..[m

-rwxr-xr-x    1 0        0          4194312 Jun  3  2005 [1;32mBigLakes2048.bin[m

-rwxr-xr-x    1 0        0              591 Jun  3  2005 [1;32mBigLakes2048.cfg[m

-rwxr-xr-x    1 0        0            56720 Mar  2  2024 [1;32mastar_base[m

-rwxr-xr-x    1 0        0              370 Mar  7  2024 [1;32mrun.sh[m

+ ./astar_base BigLakes2048.cfg

/spec/run.sh: line 14: ./astar_base: not found

+ date -R

Thu, 01 Jan 1970 00:00:19 +0000

+ set +x



> > 我在执行指令的脚本里尝试了执行ls /lib 我发现所有的动态链接库都有 但他不知道为啥就是找不到，请问是需要添加LD_LIBRARY_PATH么 如果要添加要修改哪个文件呢 ![image](https://private-user-images.githubusercontent.com/49511258/310355643-ea1b274b-505d-4dd1-b7a1-6dd58cf73d71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MzAwMTQsIm5iZiI6MTcwOTcyOTcxNCwicGF0aCI6Ii80OTUxMTI1OC8zMTAzNTU2NDMtZWExYjI3NGItNTA1ZC00ZGQxLWI3YTEtNmRkNThjZjczZDcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDEyNTUxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0MGZmYjRiMjgwMTZjY2M0ZTQ2YTMxNWJkYzRlMGM4MjQwZmRhNzFlNWZhYjMyZjZiM2RlOWUwMDM1YjRmNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.okgmTESmM5LdlmzID-34swfR1nxRSmKvS0gzuMIjg6U)
> 
> 我们建议尝试用NEMU运行ready-to-run里面的linux.bin看能否运行。
> 
> 其实Linux启动配置不属於香山这个组织应该回答的范围。虽然我们一般会尽力回答，但是你遇到的问题我们确实没遇到过，通过网络上提供的信息，我们暂时也没有什么线索。
> 
> 你遇到的这个问题也让我们意识到我们现有方式的不足：
> 
> * 文档散乱
> * 即使用户99% follow了散乱的文档，但是仍然可能因为本地其它环境导致workload生成出错。我们会在不远的未来尝试解决这个问题，比如提供docker或者虚拟机镜像。

**Comment by YudeFang** [comment]
> > 我在执行指令的脚本里尝试了执行ls /lib 我发现所有的动态链接库都有 但他不知道为啥就是找不到，请问是需要添加LD_LIBRARY_PATH么 如果要添加要修改哪个文件呢 ![image](https://private-user-images.githubusercontent.com/49511258/310355643-ea1b274b-505d-4dd1-b7a1-6dd58cf73d71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MzAwMTQsIm5iZiI6MTcwOTcyOTcxNCwicGF0aCI6Ii80OTUxMTI1OC8zMTAzNTU2NDMtZWExYjI3NGItNTA1ZC00ZGQxLWI3YTEtNmRkNThjZjczZDcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDEyNTUxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0MGZmYjRiMjgwMTZjY2M0ZTQ2YTMxNWJkYzRlMGM4MjQwZmRhNzFlNWZhYjMyZjZiM2RlOWUwMDM1YjRmNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.okgmTESmM5LdlmzID-34swfR1nxRSmKvS0gzuMIjg6U)
> 
> 我们建议尝试用NEMU运行ready-to-run里面的linux.bin看能否运行。
> 
> 其实Linux启动配置不属於香山这个组织应该回答的范围。虽然我们一般会尽力回答，但是你遇到的问题我们确实没遇到过，通过网络上提供的信息，我们暂时也没有什么线索。
> 
> 你遇到的这个问题也让我们意识到我们现有方式的不足：
> 
> * 文档散乱
> * 即使用户99% follow了散乱的文档，但是仍然可能因为本地其它环境导致workload生成出错。我们会在不远的未来尝试解决这个问题，比如提供docker或者虚拟机镜像。
astar_base这个文件通过ls命令可以看到确实存在在/spec下，并且当前工作目录通过pwd显示也在/spec下，但是执行astar_base的时候找不到这个文件

**Comment by YudeFang** [comment]
> > 我在执行指令的脚本里尝试了执行ls /lib 我发现所有的动态链接库都有 但他不知道为啥就是找不到，请问是需要添加LD_LIBRARY_PATH么 如果要添加要修改哪个文件呢 ![image](https://private-user-images.githubusercontent.com/49511258/310355643-ea1b274b-505d-4dd1-b7a1-6dd58cf73d71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MzAwMTQsIm5iZiI6MTcwOTcyOTcxNCwicGF0aCI6Ii80OTUxMTI1OC8zMTAzNTU2NDMtZWExYjI3NGItNTA1ZC00ZGQxLWI3YTEtNmRkNThjZjczZDcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDEyNTUxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0MGZmYjRiMjgwMTZjY2M0ZTQ2YTMxNWJkYzRlMGM4MjQwZmRhNzFlNWZhYjMyZjZiM2RlOWUwMDM1YjRmNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.okgmTESmM5LdlmzID-34swfR1nxRSmKvS0gzuMIjg6U)
> 
> 我们建议尝试用NEMU运行ready-to-run里面的linux.bin看能否运行。
> 
> 其实Linux启动配置不属於香山这个组织应该回答的范围。虽然我们一般会尽力回答，但是你遇到的问题我们确实没遇到过，通过网络上提供的信息，我们暂时也没有什么线索。
> 
> 你遇到的这个问题也让我们意识到我们现有方式的不足：
> 
> * 文档散乱
> * 即使用户99% follow了散乱的文档，但是仍然可能因为本地其它环境导致workload生成出错。我们会在不远的未来尝试解决这个问题，比如提供docker或者虚拟机镜像。





**astar_base这个文件通过ls命令可以看到确实存在在/spec下，并且当前工作目录通过pwd显示也在/spec下，但是执行astar_base的时候找不到这个文件**

**Comment by shinezyy** [comment]
> > > 我在执行指令的脚本里尝试了执行ls /lib 我发现所有的动态链接库都有 但他不知道为啥就是找不到，请问是需要添加LD_LIBRARY_PATH么 如果要添加要修改哪个文件呢 ![image](https://private-user-images.githubusercontent.com/49511258/310355643-ea1b274b-505d-4dd1-b7a1-6dd58cf73d71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MzAwMTQsIm5iZiI6MTcwOTcyOTcxNCwicGF0aCI6Ii80OTUxMTI1OC8zMTAzNTU2NDMtZWExYjI3NGItNTA1ZC00ZGQxLWI3YTEtNmRkNThjZjczZDcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDEyNTUxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0MGZmYjRiMjgwMTZjY2M0ZTQ2YTMxNWJkYzRlMGM4MjQwZmRhNzFlNWZhYjMyZjZiM2RlOWUwMDM1YjRmNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.okgmTESmM5LdlmzID-34swfR1nxRSmKvS0gzuMIjg6U)
> > 
> > 
> > 我们建议尝试用NEMU运行ready-to-run里面的linux.bin看能否运行。
> > 其实Linux启动配置不属於香山这个组织应该回答的范围。虽然我们一般会尽力回答，但是你遇到的问题我们确实没遇到过，通过网络上提供的信息，我们暂时也没有什么线索。
> > 你遇到的这个问题也让我们意识到我们现有方式的不足：
> > 
> > * 文档散乱
> > * 即使用户99% follow了散乱的文档，但是仍然可能因为本地其它环境导致workload生成出错。我们会在不远的未来尝试解决这个问题，比如提供docker或者虚拟机镜像。
> 
> **astar_base这个文件通过ls命令可以看到确实存在在/spec下，并且当前工作目录通过pwd显示也在/spec下，但是执行astar_base的时候找不到这个文件**

一般的，出现这种情况，要么是文件没有可执行权限，要么是指令集或者ABI不匹配

**Comment by YudeFang** [comment]
**感谢回答 能否把你们样例中的astar_base biglake2048.cfg这三个文件发一下呢 因为我感觉我的spec交叉编译是没有问题的，我无法确定这件事因为我没有riscv的机器。所以如果能测试一下你们正确的程序我可以确定是否是abi的问题**

> > > > 我在执行指令的脚本里尝试了执行ls /lib 我发现所有的动态链接库都有 但他不知道为啥就是找不到，请问是需要添加LD_LIBRARY_PATH么 如果要添加要修改哪个文件呢 ![image](https://private-user-images.githubusercontent.com/49511258/310355643-ea1b274b-505d-4dd1-b7a1-6dd58cf73d71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MzAwMTQsIm5iZiI6MTcwOTcyOTcxNCwicGF0aCI6Ii80OTUxMTI1OC8zMTAzNTU2NDMtZWExYjI3NGItNTA1ZC00ZGQxLWI3YTEtNmRkNThjZjczZDcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDEyNTUxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0MGZmYjRiMjgwMTZjY2M0ZTQ2YTMxNWJkYzRlMGM4MjQwZmRhNzFlNWZhYjMyZjZiM2RlOWUwMDM1YjRmNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.okgmTESmM5LdlmzID-34swfR1nxRSmKvS0gzuMIjg6U)
> > > 
> > > 
> > > 我们建议尝试用NEMU运行ready-to-run里面的linux.bin看能否运行。
> > > 其实Linux启动配置不属於香山这个组织应该回答的范围。虽然我们一般会尽力回答，但是你遇到的问题我们确实没遇到过，通过网络上提供的信息，我们暂时也没有什么线索。
> > > 你遇到的这个问题也让我们意识到我们现有方式的不足：
> > > 
> > > * 文档散乱
> > > * 即使用户99% follow了散乱的文档，但是仍然可能因为本地其它环境导致workload生成出错。我们会在不远的未来尝试解决这个问题，比如提供docker或者虚拟机镜像。
> > 
> > 
> > **astar_base这个文件通过ls命令可以看到确实存在在/spec下，并且当前工作目录通过pwd显示也在/spec下，但是执行astar_base的时候找不到这个文件**
> 
> 一般的，出现这种情况，要么是文件没有可执行权限，要么是指令集或者ABI不匹配

**Comment by xiaokamikami** [comment]
> **感谢回答 能否把你们样例中的astar_base biglake2048.cfg这三个文件发一下呢 因为我感觉我的spec交叉编译是没有问题的，我无法确定这件事因为我没有riscv的机器。所以如果能测试一下你们正确的程序我可以确定是否是abi的问题**
> 
> > > > > 我在执行指令的脚本里尝试了执行ls /lib 我发现所有的动态链接库都有 但他不知道为啥就是找不到，请问是需要添加LD_LIBRARY_PATH么 如果要添加要修改哪个文件呢 ![image](https://private-user-images.githubusercontent.com/49511258/310355643-ea1b274b-505d-4dd1-b7a1-6dd58cf73d71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MzAwMTQsIm5iZiI6MTcwOTcyOTcxNCwicGF0aCI6Ii80OTUxMTI1OC8zMTAzNTU2NDMtZWExYjI3NGItNTA1ZC00ZGQxLWI3YTEtNmRkNThjZjczZDcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDEyNTUxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0MGZmYjRiMjgwMTZjY2M0ZTQ2YTMxNWJkYzRlMGM4MjQwZmRhNzFlNWZhYjMyZjZiM2RlOWUwMDM1YjRmNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.okgmTESmM5LdlmzID-34swfR1nxRSmKvS0gzuMIjg6U)
> > > > 
> > > > 
> > > > 我们建议尝试用NEMU运行ready-to-run里面的linux.bin看能否运行。
> > > > 其实Linux启动配置不属於香山这个组织应该回答的范围。虽然我们一般会尽力回答，但是你遇到的问题我们确实没遇到过，通过网络上提供的信息，我们暂时也没有什么线索。
> > > > 你遇到的这个问题也让我们意识到我们现有方式的不足：
> > > > 
> > > > * 文档散乱
> > > > * 即使用户99% follow了散乱的文档，但是仍然可能因为本地其它环境导致workload生成出错。我们会在不远的未来尝试解决这个问题，比如提供docker或者虚拟机镜像。
> > > 
> > > 
> > > **astar_base这个文件通过ls命令可以看到确实存在在/spec下，并且当前工作目录通过pwd显示也在/spec下，但是执行astar_base的时候找不到这个文件**
> > 
> > 
> > 一般的，出现这种情况，要么是文件没有可执行权限，要么是指令集或者ABI不匹配

OK

**Comment by YudeFang** [comment]
I have resolve this problem , thank you all

**Comment by shinezyy** [comment]
> I have resolve this problem , thank you all

How？
Can you provide your solution, which might help others

**Comment by YudeFang** [comment]
> > I have resolve this problem , thank you all
> 
> How？ Can you provide your solution, which might help others

later I will PR to the checkpoint branch in OpenXiangShan/riscv-rootfs repository
